# Generated by Django 4.0.6 on 2022-10-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0002_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Page',
        ),
    ]
