# Generated by Django 4.0.6 on 2022-10-04 04:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0003_rename_blog_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='text_message',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
